org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Environment generated through IntelliJ IDEA Minecraft Development 2024.1-1.8.4.
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Optional development/documentation mods.
patchouli_version=1.20.1-84
jei_version=15.20.0.106
jade_version=11.13.2+forge

mod_id=openblocks_reborn
mod_name=OpenBlocks Reborn
mod_license=MIT
mod_version=1.0.0-1.20.1
mod_group_id=net.xuwu
mod_authors=lingmu
mod_description=A Forge 1.20.1 revival of the classic OpenBlocks collection.
